version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name sankawa-test --s3-location s3://sankawa-handson/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
