version: 0.2

phases:
  build:
    commands:
      - cp src/scripts/* /scripts/
      - chmod +x /scripts/*.sh
      - aws deploy push --application-name sankawa-test --s3-location s3://sankawa-handson/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
