version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name xxx --s3-location s3://sankawa-test/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
