version: 0.2

phases:
  build:
    commands:
      - mkdir -p /opt/scripts
      - mkdir -p /var/www/myapp/scripts
      - cp src/scripts/* /var/www/myapp/scripts/
      - aws deploy push --application-name sankawa-test --s3-location s3://sankawa-handson/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
