version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/

hooks:
  ValidateService:
    - location: scripts/register_to_lb.sh
      timeout: 300
      runas: root

  AfterAllowTraffic:
    - location: scripts/deregister_from_lb.sh
      timeout: 300
      runas: root
